### ISSUE TITLE
Feature request: support for setting color by scene

### ISSUE THREAD

**Issue by kevinferguson29** [timniklas/hass-govee-ble-lights#1]
It is noted in light.py that there are color change mode enums, but only manual (RGB) is supported. Requesting support for color scenes included in Govee app (Sunrise, Twinkle, Candlelight, etc).

```
class LedMode(IntEnum):
    """
    The mode in which a color change happens in.
    
    Currently only manual is supported.
    """
    MANUAL     = 0x02
    MICROPHONE = 0x06
    SCENES     = 0x05
```

**Comment by timniklas** [comment]
its currently not planned to add scene support
