### ISSUE TITLE
The controls works only occasionally

### ISSUE THREAD

**Issue by mainTAP** [timniklas/hass-govee-ble-lights#17]
The integration seems to be working 50/50, sometimes it triggers the light to go on/off but many times it doesn't and the action needs to be repeated ( Home Assistant reports as if the action worked, so for instance, if turning the light off, it needs to be turned back on and then turned off again, which usually helps to actually trigger the light)

I have Govee h6181 LED strip and ESP Home bluetooth proxy.

I was using a different integration before (https://github.com/Beshelmek/govee_ble_lights) but didn't have this issue.

**Comment by timniklas** [comment]
The linked code is actually based on my integration. But they have built in support for sending multiple commands at once, I guess that will be the difference. I will have a look at it.
Thanks for your feedback

**Comment by timniklas** [comment]
please retry with current version

**Comment by mainTAP** [comment]
Many thanks, it seems to be working perfectly so far, I'll keep testing.
