### ISSUE TITLE
Issue: Random BLE MAC Addresses instead of surrounding ones

### ISSUE THREAD

**Issue by Prash1407** [timniklas/hass-govee-ble-lights#2]
Hey Tim-Niklas,

ich habe dein Govee addon via HACS installiert, aber leider gibt er mir eine Liste von unbekannten BT MAC Adressen und Govee Geräten an, aber nicht die in seiner unmittelbaren nähe. Ist das ein Bug? Gibt es die Möglichkeit eventuell sogar manuell die MAC einzugeben?

Ich habe noch eventuell  für dich hilfreiche Ressourcen gefunden für mein spezifisches Govee RGBIC (H6127):
https://pypi.org/project/govee-api-ble/
https://github.com/BeauJBurroughs/Govee-H6127-Reverse-Engineering

Wäre eventuell hilfreich für die Weiterentwicklung dieses Add-ons.

Hoffe du schaust hier rein und kannst mir weiterhelfen.

Lg

**Comment by timniklas** [comment]
please retry with current version
