### ISSUE TITLE
Device request: LED Strip H6125

### ISSUE THREAD

**Issue by Milinator** [timniklas/hass-govee-ble-lights#7]
Would it be possible to add the LED strip H6125 to this integration?

Wäre es möglich, die Govee LED Stripes H6125 hinzuzufügen? Und wie genau funktioniert die Integration eigentlich? Wenn ich sie starte, sehe ich nichts. Ich vermute, wenn ich kompatible Lichter hätte, würden sie da angezeigt werden, richtig?

**Comment by Milinator** [comment]
I managed to do it on my own.
I changed line 5 (manifest.json) from `{ "local_name": "ihoment_*", "connectable": false }` to `{ "local_name": "GBK_*", "connectable": false }`. This way my LED stripes got auto detected (because their bluetooth name starts with GBK_). Pretty sure I had to do some more minor changes that I'm not sure about anymore, but just in case someone wants to control a different device I wanted to add that here.

**Comment by dysphasi** [comment]
@Milinator @timniklas 

There appear to be different hardware versions of the same light strip, earlier version started with "ihoment_", later strips "GBK_"

Forgive my ignorance, but how should the manifest.json be edited to allow for both versions?

Thank you to the both of you in advance!

**Comment by Milinator** [comment]
> @Milinator @timniklas 
> 
> There appear to be different hardware versions of the same light strip, earlier version started with "ihoment_", later strips "GBK_"
> 
> Forgive my ignorance, but how should the manifest.json be edited to allow for both versions?
> 
> 
> 
> Also, it appears that 'ihoment' strips can be turned on and off as well as permit changing of the colour of the lights.
> 
> However, 'GBK' strips can only be turned on and off, selecting a different colour does nothing.
> 
> 
> 
> Thank you to the both of you in advance!
> 
> 

Sorry, I'm on mobile right now, so I can't really give good advice. I'm pretty sure I did some changes in the lights.py file at the end.

Have a look at the case statement in _get_color_payload.

**Comment by dysphasi** [comment]
> > @Milinator @timniklas
> > There appear to be different hardware versions of the same light strip, earlier version started with "ihoment_", later strips "GBK_"
> > Forgive my ignorance, but how should the manifest.json be edited to allow for both versions?
> > Also, it appears that 'ihoment' strips can be turned on and off as well as permit changing of the colour of the lights.
> > However, 'GBK' strips can only be turned on and off, selecting a different colour does nothing.
> > Thank you to the both of you in advance!
> 
> Sorry, I'm on mobile right now, so I can't really give good advice. I'm pretty sure I did some changes in the lights.py file at the end.
> 
> Have a look at the case statement in _get_color_payload.

Thanks for replying!

I edited the manifest, simple enough to just add an extra line (I forgot a comma first time around...but simple enough)

However, re: getting the colour to change, I've had a look but not too sure what would need to be edited (bearing in mind I need to get both of mine working).

When you've time and back at a computer, could you possibly share your edits? It really would be appreciated!

Thank you

**Comment by Omemanti** [comment]
hey, thank god i found this thread. I have a new set of H6125. I moddified the manifest and the LED strip pops up in my list of intergrations. I can select it, and submit it, but then gives me an error. 

=> cloud not find Govee BLE device with adress .....
=> GBK_H6125_60FE no device or entities

Can someone point me in the right direction?

**Comment by timniklas** [comment]
please retry with current version
